# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Beer.destroy_all
Beer.create(title: "Hop Valley Citrus Mistress", description: "The Hop Valley Citrus Mistress IPA features 6 different hops with multiple flavours and aromas complimented with the addition of grapefruit peel. It creates a bouquet of citrus, peach and tropical fruits with enough Munich malt to produce a classic burnt orange flavour that's worthy of its name.", country: "Eugene, Oregon, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_225058")
Beer.create(title: "Cigar City Humidor Series", description: "The Humidor Series is a rotating offering of Cigar City Brewing beer aged on Spanish cedar.", country: "Tampa, Florida, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_102863")
Beer.create(title: "Ballast Point Grapefruit Sculpin", description: "Our Grapefruit Sculpin is the latest take on our signature IPA. Some may say there are few ways to improve Sculpin’s unique flavor, but the tart freshness of grapefruit perfectly complements our IPA’s citrusy hop character. Grapefruit’s a winter fruit, but this easy-drinking ale tastes like summer.", country: "San Diego, California, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_213365")
Beer.create(title: "Bell's Kalamazoo", description: "Named after the city where it all began, Kalamazoo Stout is one of our most classic recipes. This smooth, full-bodied stout offers a blend of aromas and flavors of dark chocolate and freshly roasted coffee, balanced with a significant hop presence.
", country: "Comstock, Michigan, United States", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_3209")
Beer.create(title: "Brew York Imperial Tonkoko", description: "We’ve beefed up Tonkoko and brewed an imperial version, set to launch at the 2017 Leeds International Beer Festival. Expect an even bigger coconut, Tonka, Cacao & Vanilla hit, to compliment the extra abv. Wrapped in a creamy sweet milk stout.", country: "York, North Yorkshire, England", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_554664")
Beer.create(title: "3 Sheeps Hello My Name is Joe", description: "We at 3 Sheeps love our coffee. We also love our beer. This union was inevitable. The sweet and roasty notes of the Sumatra coffee dance merrily with the smooth, roasty, and chocolate hints found in our Baaad Boy Black Wheat. If you are a coffee fan, this is not a beer you want to miss out on.", country: "Sheboygan, Wisconsin, United States", style:"Wheat Ale", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_182392")
Beer.create(title: "Marz Jungle Boogie", description: "Jungle Boogie is an American Wheat beer with just enough complex malt character to balance the juicy Mosaic hops and rooibos tea flavors.", country: "Chicago, Illinois, United States", style:"Wheat Ale", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_303531")
Beer.create(title: "Cellarmaker Bucket of Truth", description: "This hoppy wheat ale is a great summertime crusher brewed with white malted wheat and Citra. Simoe, Galaxy, Mosaic and Nelson hops. Cellarmaker Warning;you may encounter charts and the disruption of the Status Quo.", country: "San Francisco, California, United States", style:"Wheat Ale", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_280765")
Beer.create(title: "Tiger Beer", description: "Tiger was born on the hot streets of Singapore – the tropical island city state – a busy trading destination and melting pot of Asian, Indian, and British influences and culture. The ‘tropical lagering’ process brews a bravely creative and unpretentious lager. The result is the intensely refreshing, full-bodied taste of one of the world’s fastest growing premium beers.
Ingredients: Pilsner malt, corn sugar, yeast, and noble hops.", country: "Singapore, Singapore", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/d_beer_img_default.png,f_auto/beer_3126")
Beer.create(title: "San Miguel", description: "San Miguel Pale Pilsen, a pilsner popularly called San Miguel Beer, is the Company’s flagship brand and the Philippines’ leading brew. It is one of the world’s largest selling beers. Made from imported barley malt, as well as German and American hops, it is exported to over 40 countries worldwide.", country: "Mandaluyong City, Metro Manila, Philippines", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_1168")
Beer.create(title: "Asahi Super Dry", description: "Asahi Super Dry was a direct result of extensive market research which indicated a consumer preference for a more palatable beer with less maltiness, relatively high alcohol content and a light aftertaste, that paired well with the changing Japanese diet. With this insight Asahi used its brewing knowledge to develop a beer with a crisp bite, refreshing taste and clear finish to satisfied this requirement. Code named project FX, Asahi engineered a highly attenuated, highly carbonated pilsner. The later renamed product, Super Dry began sales on March 17th 1987 and gave birth to the dry beer category. The market success spawned similar competitor products and initiated what was known as the “Dry Wars” in Japan and a brief marketing fad for dry beers internationally. However Asahi has stood the test of time and now years later Super Dry continues it legacy as the world’s premier dry beer.", country: "Tokyo, Japan", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_251")
Beer.create(title: "Kirin Ichiban", description: "Finest barley malt, premium hops, smooth finish, no bitter aftertaste.", country: "Tokyo, Japan", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_268")
Beer.create(title: "Suntory The Premium Malt's", description: "The Premium Malt’s features a delicate floral aroma and a rich, quality taste. The Premium Malt’s is made from carefully selected pure ingredients using original brewing methods, in pursuit of the perfect premium beer.", country: "Osaka, Japan", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_15747")
Beer.create(title: "Sapporo Premium Beer", description: "Marketed as Sapporo Draft Beer in Japan, and as Premium Beer in North America.", country: "Tokyo, Japan", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_729")
Beer.create(title: "Corona Extra", description: "Corona Extra is the number-one selling beer in Mexico and the leading export brand from Mexico. This pilsener type beer was first brewed in 1925 by Cervecería Modelo, located in Mexico City.", country: "México DF, Mexico", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_742")
Beer.create(title: "Cass Light", description: "Cass Light is brewed with three varieties of hops and fermented at a freezing point for the first time in Korea to ensure a better taste with the best know-how and techniques. OBC’s own high-fermentation technique has made Cass Light less caloric (with its calorie down by 33%), yet tasting lighter and cleaner.", country: "Seoul, South Korea", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_143730")
Beer.create(title: "Tsingtao", description: "Tsingtao is produced with spring water from Laoshan, a mountain area famous throughout China for the purity of its water. The domestically-grown hops used to brew Tsingtao are of such high quality that they are also exported to European breweries. Tsingtao also uses the finest yeast and barley imported from Australia and Canada in its brewing process.", country: "Qinqdao, China", style:"Pale Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_730")
Beer.create(title: "Guinness Draught", description: "Usually called Draught; sometimes called Cold or Extra Cold - same beer, but served colder. Abv ranges from 4.1 to 4.3 % depending on where it was brewed - Guinness exports a hopped and concentrated wort to regional breweries who then brew it on site.", country: "Dublin, Ireland", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_1267")
Beer.create(title: "The Kernel Dry Stout Citra", description: "Pours a night black color, with a big, beige head, revealing huge bubbles while slowly collapsing. Has intense citrus aromas, reminds you more of an ipa than an actual stout. Hops slowly blend into luscious bakers chocolate among a warming roastiness. Due to the rich maltiness, fruity hops invite sappy orange to the aromas.", country: "Bermondsey, Greater London, England", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_373056")
Beer.create(title: "Bar Harbor Cadillac Mountain Stout", description: "Earning 97 out of 100 points, this locally brewed stout won the rare platinum medal at the World Beer Championships in Chicago in December 1995. Beating such world class favorites as Guinness, Sierra Nevada, Shipyard’s Bluefin and Murphy’s Irish Stout, Bar Harbor Brewing’s Cadillac Mtn. Stout was the surprise of the competition. Cadillac Mtn. Stout has come in first every year since 1995 and in 1999 was chosen one of the top 10 beers in America. Cadillac has earned the highest scores of any Maine microbrew so far, according to the Beverage Testing Institute.", country: "Bar Harbor, Maine, United States", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_4697")
Beer.create(title: "Le Naufrageur St-Barnabé", description: "All in coffee and chocolate, this oat stout has a creamy texture. Its opaque black color suggests a roasting taste and the bitterness of a good espresso coffee.", country: "Carleton-sur-Mer, Canada", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_99006")
Beer.create(title: "Schlafly Irish Style Extra Stout", description: "Pours black and is an amped-up version of a traditional dry stout. The addition of both roasted barley and dark crystal malted barley give Extra Stout undertones of chocolate, molasses and dried fruit.", country: "St. Louis, Missouri, United States", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_69547")
Beer.create(title: "Carlow O'Hara's Leann Folláin", description: "True to it’s name, “Leann Folláin” being the Gaelic for “wholesome stout”, our full-bodied extra Irish stout is a fantastic example of how good stout can taste. Flavours of dark chocolate tones with a hint of vanilla combine with the mild mocha aroma. Opaque black in appearance with a tan head, this luxurious stout has a classic European hop bitterness giving a refreshing bite after the chocolate subsides.", country: "Bagenalstown, Co. Carlow, Ireland", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_100788")
Beer.create(title: "Porterhouse Wrasslers XXXX", description: "XXXX refers to the alcohol level and the depth of flavour in this stout. Our kettle hops drum up a fabulous aroma, flaked barley delivering big time on texture and the darkly roasted grain building a flavour as solid as a rock. Not for the faint hearted. Can you handle it?", country: "Dublin, Ireland", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_11380")
Beer.create(title: "AleSmith IPA", description: "It’s Pretty Awesome. A San Diego classic, AleSmith IPA showcases the versatility of American hops. Aromas of grapefruit and tangerine lead into an abundance of fresh pine and tropical fruit notes followed by a crisp, resinous bitterness. The complex hop profile is supported by a firm malt presence to create an incredibly flavorful and well-balanced IPA.", country: "San Diego, California, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_14396")
Beer.create(title: "NoDa Hop, Drop 'n Roll", description: "For us this is where it all started! The rich golden color comes from a blend of English and American base malts accented with substantial amounts of Victory and Wheat malt. The American citrus hops take center stage with emphasis on late boil additions of Citra and Amarillo. This signature ale is hopped before, during, and after the boil!", country: "Charlotte, North Carolina, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_156010")
Beer.create(title: "The Brew Kettle White Rajah", description: "A West Coast style IPA full of citrus-like and tropical fruit-like hop flavor and aroma with an assertive yet smooth bitter finish. .....malt, take a back seat please.", country: "Strongsville, Ohio, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_132310")
Beer.create(title: "Vox Populi Vox Pop IPA - Citra", description: "An educative and interactive project, this IPA changes with each batch for us to discover the aromatic virtues of various hop varietals.  Come and vote for your favorite hops on our Facebook page!", country: "Montréal, Quebec, Canada", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_492235")
Beer.create(title: "Lawson's Finest Chinookerd", description: "Limited release! Our award-winning single-hop India Pale Ale is a hop lover’s delight!", country: "Waitsfield, Vermont, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_92737")
Beer.create(title: "Port Brewing Wipeout", description: "With 78 IBUs. Our version of a West Coast IPA- brewed in the San Diego style. This massively hoppy beer gets its flavor and attitude from no less than five hop varieties including Amarillo, Centennial, Cascade, Simcoe and Summit.", country: "San Marcos, California, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_14434")
p "SEEDED BEERS DATA"

Guide.destroy_all
Guide.create(title: "John's review", description:"I love brewing my own beers.", image:"https://cdn2us.denofgeek.com/sites/denofgeekus/files/styles/main_wide/public/2019/01/jeff-bridges-dude-big-lebowski.jpg?itok=zPqud1Gy")
Guide.create(title: "Jesus's review", description:"Let there be beer.", image:"https://www.testifygod.org/wp-content/uploads/2018/08/Lord-Jesus.jpg")

p "SEEDED GUIDES DATA"

