# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Beer.destroy_all
Beer.create(title: "8 Wired iStout", description: "Beware, this is a BIG beer. Brimming with luscious roasted coffee and chocolate malt flavours which are balanced by a brisk bitterness and bold freshness from the hops.", country: "Warkworth, New Zealand", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_122165", region: "Oceania")
Beer.create(title: "Coopers Best Extra Stout", description: "Coopers Stout is a beacon for lovers of a hearty brew. With its robust flavour comprising a blend of fruit, chocolate and hop bitter notes it’s everything a stout should be.", country: "Regency Park, South Australia, Australia", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_1590", region: "Oceania")
Beer.create(title: "Carlton Draught", description: "This traditional full strength lager, available nationally, is renowned for delivering a brewery fresh taste. Carlton Draught provides a crisp mid-palate flavour which is balanced with a clean hop bitterness and a slightly dry finish.", country: "Melbourne, Victoria, Australia", style:"Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_7179", region: "Oceania")
Beer.create(title: "Little Creatures IPA", description: "Sitting alongside our Pale Ale, the IPA will deliver the big, rugged hop flavours and the citrusy nose that you would expect. However you’ll also detect aniseed and savoury notes, balanced out with a long firm bitterness to finish.", country: "Fremantle, Australia", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_227925", region: "Oceania")
Beer.create(title: "Hop Valley Citrus Mistress", description: "The Hop Valley Citrus Mistress IPA features 6 different hops with multiple flavours and aromas complimented with the addition of grapefruit peel. It creates a bouquet of citrus, peach and tropical fruits with enough Munich malt to produce a classic burnt orange flavour that's worthy of its name.", country: "Eugene, Oregon, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_225058", region: "North America")
Beer.create(title: "Cigar City Humidor Series", description: "The Humidor Series is a rotating offering of Cigar City Brewing beer aged on Spanish cedar.", country: "Tampa, Florida, United States", style:"IPA", image:"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKCxcJlsGfsW4h8H56Mm_fBJK_u4pDCh_V5TgILjctMo1WaJLaoH5ByQg", region: "North America")
Beer.create(title: "Ballast Point Grapefruit Sculpin", description: "Our Grapefruit Sculpin is the latest take on our signature IPA. Some may say there are few ways to improve Sculpin’s unique flavor, but the tart freshness of grapefruit perfectly complements our IPA’s citrusy hop character.", country: "San Diego, California, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_213365", region: "North America")
Beer.create(title: "Bell's Kalamazoo", description: "Named after the city where it all began, Kalamazoo Stout is one of our most classic recipes. This smooth, full-bodied stout offers a blend of aromas and flavors of dark chocolate and freshly roasted coffee, balanced with a significant hop presence.", country: "Comstock, Michigan, United States", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_3209", region: "North America")
Beer.create(title: "Brew York Imperial Tonkoko", description: "We’ve beefed up Tonkoko and brewed an imperial version, set to launch at the 2017 Leeds International Beer Festival. Expect an even bigger coconut, Tonka, Cacao & Vanilla hit, to compliment the extra abv. Wrapped in a creamy sweet milk stout.", country: "York, North Yorkshire, England", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_554664", region: "Europe")
Beer.create(title: "3 Sheeps Hello My Name is Joe", description: "We at 3 Sheeps love our coffee. We also love our beer. This union was inevitable. The sweet and roasty notes of the Sumatra coffee dance merrily with the smooth, roasty, and chocolate hints found in our Baaad Boy Black Wheat.", country: "Sheboygan, Wisconsin, United States", style:"Wheat Ale", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_182392", region: "North America")
Beer.create(title: "Marz Jungle Boogie", description: "Jungle Boogie is an American Wheat beer with just enough complex malt character to balance the juicy Mosaic hops and rooibos tea flavors.", country: "Chicago, Illinois, United States", style:"Wheat Ale", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_303531", region: "North America")
Beer.create(title: "Cellarmaker Bucket of Truth", description: "This hoppy wheat ale is a great summertime crusher brewed with white malted wheat and Citra. Simoe, Galaxy, Mosaic and Nelson hops. Cellarmaker Warning;you may encounter charts and the disruption of the Status Quo.", country: "San Francisco, California, United States", style:"Wheat Ale", image:"https://untappd.akamaized.net/photos/2019_08_14/c2b7cfda1bfcbfdf34b6ed0dc33f9ff5_640x640.jpg", region: "North America")
Beer.create(title: "Tiger Beer", description: "Tiger was born on the hot streets of Singapore – the tropical island city state – a busy trading destination and melting pot of Asian, Indian, and British influences and culture. The ‘tropical lagering’ process brews a bravely creative and unpretentious lager.", country: "Singapore, Singapore", style:"Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/d_beer_img_default.png,f_auto/beer_3126", region: "Asia")
Beer.create(title: "San Miguel", description: "San Miguel Pale Pilsen, a pilsner popularly called San Miguel Beer, is the Company’s flagship brand and the Philippines’ leading brew. Made from imported barley malt, as well as German and American hops, it is exported to over 40 countries worldwide.", country: "Mandaluyong City, Metro Manila, Philippines", style:"Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_1168", region: "Asia")
Beer.create(title: "Asahi Super Dry", description: "Code named project FX, Asahi engineered a highly attenuated, highly carbonated pilsner.", country: "Tokyo, Japan", style:"Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_251", region: "Asia")
Beer.create(title: "Kirin Ichiban", description: "Finest barley malt, premium hops, smooth finish, no bitter aftertaste.", country: "Tokyo, Japan", style:"Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_268", region: "Asia")
Beer.create(title: "Suntory The Premium Malt's", description: "The Premium Malt’s features a delicate floral aroma and a rich, quality taste. The Premium Malt’s is made from carefully selected pure ingredients using original brewing methods, in pursuit of the perfect premium beer.", country: "Osaka, Japan", style:"Lager", image:"https://cdn.beercellar.com/products/2000/2117_1500H.jpg", region: "Asia")
Beer.create(title: "Sapporo Premium Beer", description: "Marketed as Sapporo Draft Beer in Japan, and as Premium Beer in North America.", country: "Tokyo, Japan", style:"Lager", image:"https://cdn.shopify.com/s/files/1/1564/3513/products/Sapporo_Premium_Beer_Bottle_1024x1024.jpg?v=1522990262", region: "Asia")
Beer.create(title: "Corona Extra", description: "Corona Extra is the number-one selling beer in Mexico and the leading export brand from Mexico. This pilsener type beer was first brewed in 1925 by Cervecería Modelo, located in Mexico City.", country: "México DF, Mexico", style:"Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_742", region: "South America")
Beer.create(title: "Cass Light", description: "Cass Light is brewed with three varieties of hops and fermented at a freezing point for the first time in Korea to ensure a better taste with the best know-how and techniques.", country: "Seoul, South Korea", style:"Lager", image:"https://www.wishbeer.com/2040/cass-fresh-330-ml-45.jpg", region: "Asia")
Beer.create(title: "Tsingtao", description: "Tsingtao is produced with spring water from Laoshan, a mountain area famous throughout China for the purity of its water. The domestically-grown hops used to brew Tsingtao are of such high quality that they are also exported to European breweries.", country: "Qinqdao, China", style:"Lager", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_730", region: "Asia")
Beer.create(title: "Guinness Draught", description: "Usually called Draught; sometimes called Cold or Extra Cold - same beer, but served colder. Abv ranges from 4.1 to 4.3 % depending on where it was brewed - Guinness exports a hopped and concentrated wort to regional breweries who then brew it on site.", country: "Dublin, Ireland", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:15/d_beer_img_default.png,f_auto/beer_19433", region: "Europe")
Beer.create(title: "The Kernel Dry Stout Citra", description: "Pours a night black color, with a big, beige head, revealing huge bubbles while slowly collapsing. Has intense citrus aromas, reminds you more of an ipa than an actual stout. Hops slowly blend into luscious bakers chocolate among a warming roastiness.", country: "Bermondsey, Greater London, England", style:"Stout", image:"https://www.craftmetropolis.co.uk/app/uploads/2019/02/388B5146-400x800.jpg", region: "Europe")
Beer.create(title: "Bar Harbor Cadillac Mountain Stout", description: "Earning 97 out of 100 points, this locally brewed stout won the rare platinum medal at the World Beer Championships in Chicago in December 1995. Cadillac Mtn. Stout has come in first every year since 1995 and in 1999 was chosen one of the top 10 beers in America.", country: "Bar Harbor, Maine, United States", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_4697", region: "North America")
Beer.create(title: "Le Naufrageur St-Barnabé", description: "All in coffee and chocolate, this oat stout has a creamy texture. Its opaque black color suggests a roasting taste and the bitterness of a good espresso coffee.", country: "Carleton-sur-Mer, Canada", style:"Stout", image:"https://img.saveur-biere.com/img/p/10335-22402.jpg", region: "North America")
Beer.create(title: "Schlafly Irish Style Extra Stout", description: "Pours black and is an amped-up version of a traditional dry stout. The addition of both roasted barley and dark crystal malted barley give Extra Stout undertones of chocolate, molasses and dried fruit.", country: "St. Louis, Missouri, United States", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_69547", region: "North America")
Beer.create(title: "Carlow O'Hara's Leann Folláin", description: "Flavours of dark chocolate tones with a hint of vanilla combine with the mild mocha aroma. Opaque black in appearance with a tan head, this luxurious stout has a classic European hop bitterness giving a refreshing bite after the chocolate subsides.", country: "Bagenalstown, Co. Carlow, Ireland", style:"Stout", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_100788", region: "Europe")
Beer.create(title: "Porterhouse Wrasslers XXXX", description: "Our kettle hops drum up a fabulous aroma, flaked barley delivering big time on texture and the darkly roasted grain building a flavour as solid as a rock.", country: "Dublin, Ireland", style:"Stout", image:"https://images-nitrosell-com.akamaized.net/product_images/9/2091/large-porterhouse-wrasslers-xxx.jpg", region: "Europe")
Beer.create(title: "AleSmith IPA", description: "A San Diego classic, AleSmith IPA showcases the versatility of American hops. Aromas of grapefruit and tangerine lead into an abundance of fresh pine and tropical fruit notes followed by a crisp, resinous bitterness.", country: "San Diego, California, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_14396", region: "North America")
Beer.create(title: "NoDa Hop, Drop 'n Roll", description: "The rich golden color comes from a blend of English and American base malts accented with substantial amounts of Victory and Wheat malt. The American citrus hops take center stage with emphasis on late boil additions of Citra and Amarillo.", country: "Charlotte, North Carolina, United States", style:"IPA", image:"https://images.ctfassets.net/qe08557i7rmu/VsdpKicAAMYApt1p/b56fdd1d238f442ecb7d748a0cd03c1c/a6cbc515f6d1c45e3c60de26b42d23e227c591db_noda-hop-drop--roll-ipa_4x6.jpg?w=900", region: "North America")
Beer.create(title: "The Brew Kettle White Rajah", description: "A West Coast style IPA full of citrus-like and tropical fruit-like hop flavor and aroma with an assertive yet smooth bitter finish. .....malt, take a back seat please.", country: "Strongsville, Ohio, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_132310", region: "North America")
Beer.create(title: "Vox Populi Vox Pop IPA - Citra", description: "An educative and interactive project, this IPA changes with each batch for us to discover the aromatic virtues of various hop varietals.  Come and vote for your favorite hops on our Facebook page!", country: "Montréal, Quebec, Canada", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:15/d_beer_img_default.png,f_auto/beer_515943", region: "North America")
Beer.create(title: "Lawson's Finest Chinookerd", description: "Limited release! Our award-winning single-hop India Pale Ale is a hop lover’s delight!", country: "Waitsfield, Vermont, United States", style:"IPA", image:"https://res.cloudinary.com/ratebeer/image/upload/e_trim:1/d_beer_img_default.png,f_auto/beer_92737", region: "North America")
Beer.create(title: "Port Brewing Wipeout", description: "With 78 IBUs. Our version of a West Coast IPA- brewed in the San Diego style. This massively hoppy beer gets its flavor and attitude from no less than five hop varieties including Amarillo, Centennial, Cascade, Simcoe and Summit.", country: "San Marcos, California, United States", style:"IPA", image:"https://images-na.ssl-images-amazon.com/images/I/7128L6re4yL._SL1500_.jpg", region: "North America")
p "SEEDED BEERS DATA"

